### ISSUE TITLE
demo.py, ModuleNotFoundError: No module named 'keyboard'

### ISSUE THREAD

**Issue by voidwyrm-2** [TheNebulo/Turtle3D#1]
keyboard module doesn't exist, what python interpreter/compiler was used for this?

**Comment by NebuloDev** [comment]
> keyboard module doesn't exist, what python interpreter/compiler was used for this?

Apologies, it's an external module from PIP. I will add to the requirements.txt file. It's solely used for reading keyboard inputs and can be replaced with other modules pynput.
